# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest' # or 'ubuntu-latest' for Linux

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        echo Build steps
      displayName: 'Build'

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: |
        # Install Newman globally
        npm install -g newman
      displayName: 'Install Newman'

    - script: |
        # Run Postman collection using Newman
        ls
        cd $(System.DefaultWorkingDirectory)/DLSExam/Postman
        newman run DLSExam.postman_collection.json
      displayName: 'Run Postman Collection'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: |
        echo Deployment steps
      displayName: 'Deploy'
