version: "3.9"

services:
  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    deploy:
      replicas: 1

  api-gateway-service:
    build:
      context: .
      dockerfile: ApiGatewayService/Dockerfile
    ports:
    - 9005:80
   
  frontend-service:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
    - 9003:80