version: "3.9"

services:
  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
    - 9001:80

  api-gateway-service:
    build:
      context: .
      dockerfile: ApiGatewayService/Dockerfile
    ports:
    - 9005:80
   
  frontend-service:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
    - 9003:80

  user-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "user-database"
      MYSQL_USER: "userdb"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - user_data:/userdata

  roulette-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "roulette-database"
      MYSQL_USER: "roulettedb"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - roulette_data:/roulettedata

volumes:
  user_data:
  roulette_data:  