version: "3.9"

services:
  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
    - 9001:80

  roulette-service:
    build:
      context: .
      dockerfile: RouletteService/Dockerfile
    ports:
    - 9002:80

  api-gateway-service:
    build:
      context: .
      dockerfile: ApiGatewayService/Dockerfile
    ports:
    - 9005:80

  frontend-service:
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    ports:
    - 9003:80

  user-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "user-database"
      MYSQL_USER: "userdb"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - user_data:/userdata

  roulette-db:
    image: "mysql"
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: "roulette-database"
      MYSQL_USER: "roulettedb"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - roulette_data:/roulettedata


  seq-service:
    image: datalust/seq
    ports:
    - 9004:80
    volumes:
    - seq_data:/data
    environment:
    - ACCEPT_EULA=Y 
  zipkin-service:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
    volumes:
    - zipkin_data:/data

volumes:
  user_data:
  roulette_data:  
  seq_data:
  zipkin_data: