version: "3.9"

services:
  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
    - 9001:80

  roulette-service:
    build:
      context: .
      dockerfile: RouletteService/Dockerfile
    ports:
    - 9002:80

  api-gateway-service:
    build:
      context: .
      dockerfile: ApiGatewayService/Dockerfile
    ports:
    - 9005:80

  frontend-service:
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    ports:
    - 9003:80

 

  seq-service:
    image: datalust/seq
    ports:
    - 9004:80
    volumes:
    - seq_data:/data
    environment:
    - ACCEPT_EULA=Y 
  zipkin-service:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
    volumes:
    - zipkin_data:/data

volumes:
  user_data:
  roulette_data:  
  seq_data:
  zipkin_data: